### ISSUE TITLE
Split long a long SMS into multiple SMS

### ISSUE THREAD

**Issue by MFreeze** [try2codesecure/ShellMS#4] opened 2015-07-24 09:00 UTC
When I try to send long SMS with shellMS, the latter is split into numerous short SMS with arbitrarily length. For instance a message with 206 characters is split into 2 SMS: the first one with 160 characters and the other with 46. But the next sms I sent with 262 characters has been split into 4 sms with length respectively : 67, 68, 69 and 57 characters.

**Comment by bmintz** [comment] 2015-09-16 12:08
That didn't happen for me. It sent only two messages when I did that on version 1.3.

BTW, I tested it in bash using `am startservice --user 0 -n com.android.shellms/.sendSMS -e contact "My phone number" -e msg $(printf '=%.0s' {1..262})`.

I got two messages totaling 262 '='.

**Comment by try2codesecure** [comment] 2015-09-20 13:21
Thanks for testing "bmintz". I also can't reproduce this behavior with version 1.3. 
Maybe the meanwhile removed "PhoneNumberUtils.formatNumber" function produced this behavior.
MFreeze, How and with which version do you tested this failure?
I close this ticket for now.

**Closed by try2codesecure** 2015-09-20 13:21 UTC
